# Generated by Django 5.0.2 on 2025-03-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_night',
            field=models.IntegerField(default=0),
        ),
    ]
